name: Craig test

on:
  push:
    branches:
      - master

jobs:
  unit_tests:
    name: Gradle managed devices test
    runs-on: macos-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Managed device setup
        run: ./gradlew -Pandroid.experimental.androidTest.useUnifiedTestPlatform=true :app:pixel2api29Setup

      - name: Test Command
        run: ./gradlew -Pandroid.experimental.androidTest.useUnifiedTestPlatform=true :app:pixel2api29DebugAndroidTest